---
- name: template mariadb repo file
  template:
    src: mariadb.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo
    owner: root
    group: root
    mode: 0644

- name: install MariaDB server
  yum:
    name: [ 'mariadb-server','MariaDB-client' ]
    state: latest
  notify:
    - restart mariadb

- name: start and enable mariadb service
  service:
    name: mariadb
    state: started
    enabled: true
